create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
create table brick (id integer not null, code integer not null, color varchar(255), name varchar(255), primary key (id));
create table inventory (id integer not null, part_id integer, set_id integer, brick_id integer, inventory_set_number varchar(255), primary key (id));
create table lego_set (number varchar(255) not null, name varchar(255), year integer not null, primary key (number));
alter table inventory add constraint FK8n3ij7pcjjcunamb95yohjuei foreign key (brick_id) references brick;
alter table inventory add constraint FKdl1l5o498c1slwppgihiciqsf foreign key (inventory_set_number) references lego_set;
